package fopclient

import (
	"context"
	"fmt"
	"net/http"

	"golang.org/x/oauth2"

	"tcg-service/internal/config"
)

// Client is an authenticated HTTP client for the FOP API (BRD FR-024).
// Typed per-operation methods (wholesale-products, sales-order, etc.) are
// generated by oapi-codegen against contracts/fop/fop-oas-v0.4.0.json in
// later stories (SP-05, SP-07, SP-13); this SP-01 slice provides the
// authenticated transport those generated operations run on.
type Client struct {
	HTTPClient *http.Client
	BaseURL    string
}

// NewClient builds a Client whose HTTPClient injects an Azure AD OAuth2
// Bearer token (client credentials grant, auto-refreshed) and the
// config-driven partnerId query parameter on every outbound request.
func NewClient(ctx context.Context, cfg *config.Config) (*Client, error) {
	if cfg == nil {
		return nil, fmt.Errorf("fop client: nil config")
	}
	if err := cfg.Validate(); err != nil {
		return nil, err
	}
	transport := &oauth2.Transport{
		Source: tokenSource(ctx, cfg),
		Base:   newPartnerIDTransport(http.DefaultTransport, cfg.PartnerID),
	}
	return &Client{
		HTTPClient: &http.Client{Transport: transport},
		BaseURL:    cfg.FOPBaseURL,
	}, nil
}

// Do sends req through the authenticated, partnerId-tagged transport. The
// oauth2.Transport surfaces a token-acquisition failure as an error from Do
// without ever sending req to FOP (TC-004).
func (c *Client) Do(req *http.Request) (*http.Response, error) {
	return c.HTTPClient.Do(req)
}
